# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=3500, null=True)),
                ('autor', models.CharField(blank=True, max_length=255, null=True)),
                ('voto_positivo', models.IntegerField(blank=True, null=True)),
                ('voto_negativo', models.IntegerField(blank=True, null=True)),
                ('nota', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recomenda', models.CharField(blank=True, max_length=100, null=True)),
                ('importancia', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=3500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('caracteristicas', models.CharField(blank=True, max_length=3500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='topx.Tipo'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topx.Produto'),
        ),
    ]
