# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='polaridade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
