# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topx', '0003_produto_pol_caracteristica'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='reputacaoAutor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
