# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topx', '0004_comentario_reputacaoautor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('recomendacao', models.CharField(blank=True, max_length=255, null=True)),
                ('num_reclamacoes', models.IntegerField(blank=True, null=True)),
                ('num_antendidas', models.IntegerField(blank=True, null=True)),
                ('num_nao_atendidas', models.IntegerField(blank=True, null=True)),
                ('tempo_resposta', models.CharField(blank=True, max_length=50, null=True)),
                ('nota_comsumidor', models.FloatField(blank=True, null=True)),
                ('num_avaliacoes', models.IntegerField(blank=True, null=True)),
                ('reclamacoes_atendidas', models.FloatField(blank=True, null=True)),
                ('volta_negocio', models.FloatField(blank=True, null=True)),
                ('indice_solucao', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='url_imagem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
