# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topx', '0008_auto_20160727_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='reclamacoes_atendidas',
            new_name='pct_atentidas',
        ),
    ]
