# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topx', '0009_auto_20160727_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='url_imagem',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
