# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topx', '0010_auto_20160727_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='pct_atentidas',
            new_name='pct_atendidas',
        ),
    ]
